// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sql_service.proto

#include "sql_service.pb.h"
#include "sql_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sqlservice {

static const char* QueryRouter_method_names[] = {
  "/sqlservice.QueryRouter/ExecuteQuery",
};

std::unique_ptr< QueryRouter::Stub> QueryRouter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QueryRouter::Stub> stub(new QueryRouter::Stub(channel, options));
  return stub;
}

QueryRouter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteQuery_(QueryRouter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status QueryRouter::Stub::ExecuteQuery(::grpc::ClientContext* context, const ::sqlservice::QueryRequest& request, ::sqlservice::QueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sqlservice::QueryRequest, ::sqlservice::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteQuery_, context, request, response);
}

void QueryRouter::Stub::async::ExecuteQuery(::grpc::ClientContext* context, const ::sqlservice::QueryRequest* request, ::sqlservice::QueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sqlservice::QueryRequest, ::sqlservice::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, std::move(f));
}

void QueryRouter::Stub::async::ExecuteQuery(::grpc::ClientContext* context, const ::sqlservice::QueryRequest* request, ::sqlservice::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sqlservice::QueryResponse>* QueryRouter::Stub::PrepareAsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::sqlservice::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sqlservice::QueryResponse, ::sqlservice::QueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sqlservice::QueryResponse>* QueryRouter::Stub::AsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::sqlservice::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

QueryRouter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QueryRouter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QueryRouter::Service, ::sqlservice::QueryRequest, ::sqlservice::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QueryRouter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sqlservice::QueryRequest* req,
             ::sqlservice::QueryResponse* resp) {
               return service->ExecuteQuery(ctx, req, resp);
             }, this)));
}

QueryRouter::Service::~Service() {
}

::grpc::Status QueryRouter::Service::ExecuteQuery(::grpc::ServerContext* context, const ::sqlservice::QueryRequest* request, ::sqlservice::QueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sqlservice

