// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker_service.proto
// Protobuf C++ Version: 5.28.3

#include "worker_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace workerservice {

inline constexpr WorkerQueryRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        start_eid_{::int64_t{0}},
        end_eid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WorkerQueryRequest::WorkerQueryRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WorkerQueryRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WorkerQueryRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorkerQueryRequestDefaultTypeInternal() {}
  union {
    WorkerQueryRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorkerQueryRequestDefaultTypeInternal _WorkerQueryRequest_default_instance_;

inline constexpr Event::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        eid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Event::Event(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDefaultTypeInternal() {}
  union {
    Event _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDefaultTypeInternal _Event_default_instance_;

inline constexpr WorkerQueryResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : events_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WorkerQueryResponse::WorkerQueryResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WorkerQueryResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WorkerQueryResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorkerQueryResponseDefaultTypeInternal() {}
  union {
    WorkerQueryResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorkerQueryResponseDefaultTypeInternal _WorkerQueryResponse_default_instance_;
}  // namespace workerservice
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_worker_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_worker_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_worker_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::workerservice::WorkerQueryRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::workerservice::WorkerQueryRequest, _impl_.cid_),
        PROTOBUF_FIELD_OFFSET(::workerservice::WorkerQueryRequest, _impl_.start_eid_),
        PROTOBUF_FIELD_OFFSET(::workerservice::WorkerQueryRequest, _impl_.end_eid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::workerservice::WorkerQueryResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::workerservice::WorkerQueryResponse, _impl_.events_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::workerservice::Event, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::workerservice::Event, _impl_.eid_),
        PROTOBUF_FIELD_OFFSET(::workerservice::Event, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::workerservice::WorkerQueryRequest)},
        {11, -1, -1, sizeof(::workerservice::WorkerQueryResponse)},
        {20, -1, -1, sizeof(::workerservice::Event)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::workerservice::_WorkerQueryRequest_default_instance_._instance,
    &::workerservice::_WorkerQueryResponse_default_instance_._instance,
    &::workerservice::_Event_default_instance_._instance,
};
const char descriptor_table_protodef_worker_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024worker_service.proto\022\rworkerservice\"E\n"
    "\022WorkerQueryRequest\022\013\n\003cid\030\001 \001(\t\022\021\n\tstar"
    "t_eid\030\002 \001(\003\022\017\n\007end_eid\030\003 \001(\003\";\n\023WorkerQu"
    "eryResponse\022$\n\006events\030\001 \003(\0132\024.workerserv"
    "ice.Event\"\"\n\005Event\022\013\n\003eid\030\001 \001(\003\022\014\n\004data\030"
    "\002 \001(\t2g\n\rWorkerService\022V\n\rGetReplayData\022"
    "!.workerservice.WorkerQueryRequest\032\".wor"
    "kerservice.WorkerQueryResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_worker_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_worker_5fservice_2eproto = {
    false,
    false,
    318,
    descriptor_table_protodef_worker_5fservice_2eproto,
    "worker_service.proto",
    &descriptor_table_worker_5fservice_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_worker_5fservice_2eproto::offsets,
    file_level_enum_descriptors_worker_5fservice_2eproto,
    file_level_service_descriptors_worker_5fservice_2eproto,
};
namespace workerservice {
// ===================================================================

class WorkerQueryRequest::_Internal {
 public:
};

WorkerQueryRequest::WorkerQueryRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:workerservice.WorkerQueryRequest)
}
inline PROTOBUF_NDEBUG_INLINE WorkerQueryRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::workerservice::WorkerQueryRequest& from_msg)
      : cid_(arena, from.cid_),
        _cached_size_{0} {}

WorkerQueryRequest::WorkerQueryRequest(
    ::google::protobuf::Arena* arena,
    const WorkerQueryRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorkerQueryRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_eid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, start_eid_),
           offsetof(Impl_, end_eid_) -
               offsetof(Impl_, start_eid_) +
               sizeof(Impl_::end_eid_));

  // @@protoc_insertion_point(copy_constructor:workerservice.WorkerQueryRequest)
}
inline PROTOBUF_NDEBUG_INLINE WorkerQueryRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : cid_(arena),
        _cached_size_{0} {}

inline void WorkerQueryRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_eid_),
           0,
           offsetof(Impl_, end_eid_) -
               offsetof(Impl_, start_eid_) +
               sizeof(Impl_::end_eid_));
}
WorkerQueryRequest::~WorkerQueryRequest() {
  // @@protoc_insertion_point(destructor:workerservice.WorkerQueryRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void WorkerQueryRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.cid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    WorkerQueryRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_WorkerQueryRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &WorkerQueryRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<WorkerQueryRequest>(),
            ::google::protobuf::Message::GetNewImpl<WorkerQueryRequest>(),
            ::google::protobuf::Message::GetClearImpl<WorkerQueryRequest>(), &WorkerQueryRequest::ByteSizeLong,
                &WorkerQueryRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_._cached_size_),
            false,
        },
        &WorkerQueryRequest::kDescriptorMethods,
        &descriptor_table_worker_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* WorkerQueryRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 44, 2> WorkerQueryRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::workerservice::WorkerQueryRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string cid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.cid_)}},
    // int64 start_eid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WorkerQueryRequest, _impl_.start_eid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.start_eid_)}},
    // int64 end_eid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WorkerQueryRequest, _impl_.end_eid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.end_eid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string cid = 1;
    {PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.cid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 start_eid = 2;
    {PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.start_eid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 end_eid = 3;
    {PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.end_eid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\40\3\0\0\0\0\0\0"
    "workerservice.WorkerQueryRequest"
    "cid"
  }},
};

PROTOBUF_NOINLINE void WorkerQueryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:workerservice.WorkerQueryRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cid_.ClearToEmpty();
  ::memset(&_impl_.start_eid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.end_eid_) -
      reinterpret_cast<char*>(&_impl_.start_eid_)) + sizeof(_impl_.end_eid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WorkerQueryRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WorkerQueryRequest& this_ = static_cast<const WorkerQueryRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WorkerQueryRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WorkerQueryRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:workerservice.WorkerQueryRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string cid = 1;
          if (!this_._internal_cid().empty()) {
            const std::string& _s = this_._internal_cid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "workerservice.WorkerQueryRequest.cid");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int64 start_eid = 2;
          if (this_._internal_start_eid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_start_eid(), target);
          }

          // int64 end_eid = 3;
          if (this_._internal_end_eid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_end_eid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:workerservice.WorkerQueryRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WorkerQueryRequest::ByteSizeLong(const MessageLite& base) {
          const WorkerQueryRequest& this_ = static_cast<const WorkerQueryRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WorkerQueryRequest::ByteSizeLong() const {
          const WorkerQueryRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:workerservice.WorkerQueryRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string cid = 1;
            if (!this_._internal_cid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_cid());
            }
            // int64 start_eid = 2;
            if (this_._internal_start_eid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_start_eid());
            }
            // int64 end_eid = 3;
            if (this_._internal_end_eid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_end_eid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WorkerQueryRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WorkerQueryRequest*>(&to_msg);
  auto& from = static_cast<const WorkerQueryRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:workerservice.WorkerQueryRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_cid().empty()) {
    _this->_internal_set_cid(from._internal_cid());
  }
  if (from._internal_start_eid() != 0) {
    _this->_impl_.start_eid_ = from._impl_.start_eid_;
  }
  if (from._internal_end_eid() != 0) {
    _this->_impl_.end_eid_ = from._impl_.end_eid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WorkerQueryRequest::CopyFrom(const WorkerQueryRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:workerservice.WorkerQueryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorkerQueryRequest::InternalSwap(WorkerQueryRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cid_, &other->_impl_.cid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.end_eid_)
      + sizeof(WorkerQueryRequest::_impl_.end_eid_)
      - PROTOBUF_FIELD_OFFSET(WorkerQueryRequest, _impl_.start_eid_)>(
          reinterpret_cast<char*>(&_impl_.start_eid_),
          reinterpret_cast<char*>(&other->_impl_.start_eid_));
}

::google::protobuf::Metadata WorkerQueryRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WorkerQueryResponse::_Internal {
 public:
};

WorkerQueryResponse::WorkerQueryResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:workerservice.WorkerQueryResponse)
}
inline PROTOBUF_NDEBUG_INLINE WorkerQueryResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::workerservice::WorkerQueryResponse& from_msg)
      : events_{visibility, arena, from.events_},
        _cached_size_{0} {}

WorkerQueryResponse::WorkerQueryResponse(
    ::google::protobuf::Arena* arena,
    const WorkerQueryResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorkerQueryResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:workerservice.WorkerQueryResponse)
}
inline PROTOBUF_NDEBUG_INLINE WorkerQueryResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : events_{visibility, arena},
        _cached_size_{0} {}

inline void WorkerQueryResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
WorkerQueryResponse::~WorkerQueryResponse() {
  // @@protoc_insertion_point(destructor:workerservice.WorkerQueryResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void WorkerQueryResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    WorkerQueryResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_WorkerQueryResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &WorkerQueryResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<WorkerQueryResponse>(),
            ::google::protobuf::Message::GetNewImpl<WorkerQueryResponse>(),
            ::google::protobuf::Message::GetClearImpl<WorkerQueryResponse>(), &WorkerQueryResponse::ByteSizeLong,
                &WorkerQueryResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(WorkerQueryResponse, _impl_._cached_size_),
            false,
        },
        &WorkerQueryResponse::kDescriptorMethods,
        &descriptor_table_worker_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* WorkerQueryResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> WorkerQueryResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::workerservice::WorkerQueryResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .workerservice.Event events = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(WorkerQueryResponse, _impl_.events_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .workerservice.Event events = 1;
    {PROTOBUF_FIELD_OFFSET(WorkerQueryResponse, _impl_.events_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::workerservice::Event>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void WorkerQueryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:workerservice.WorkerQueryResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.events_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WorkerQueryResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WorkerQueryResponse& this_ = static_cast<const WorkerQueryResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WorkerQueryResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WorkerQueryResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:workerservice.WorkerQueryResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .workerservice.Event events = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_events_size());
               i < n; i++) {
            const auto& repfield = this_._internal_events().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:workerservice.WorkerQueryResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WorkerQueryResponse::ByteSizeLong(const MessageLite& base) {
          const WorkerQueryResponse& this_ = static_cast<const WorkerQueryResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WorkerQueryResponse::ByteSizeLong() const {
          const WorkerQueryResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:workerservice.WorkerQueryResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .workerservice.Event events = 1;
             {
              total_size += 1UL * this_._internal_events_size();
              for (const auto& msg : this_._internal_events()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WorkerQueryResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WorkerQueryResponse*>(&to_msg);
  auto& from = static_cast<const WorkerQueryResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:workerservice.WorkerQueryResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_events()->MergeFrom(
      from._internal_events());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WorkerQueryResponse::CopyFrom(const WorkerQueryResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:workerservice.WorkerQueryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorkerQueryResponse::InternalSwap(WorkerQueryResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.events_.InternalSwap(&other->_impl_.events_);
}

::google::protobuf::Metadata WorkerQueryResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Event::_Internal {
 public:
};

Event::Event(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:workerservice.Event)
}
inline PROTOBUF_NDEBUG_INLINE Event::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::workerservice::Event& from_msg)
      : data_(arena, from.data_),
        _cached_size_{0} {}

Event::Event(
    ::google::protobuf::Arena* arena,
    const Event& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Event* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.eid_ = from._impl_.eid_;

  // @@protoc_insertion_point(copy_constructor:workerservice.Event)
}
inline PROTOBUF_NDEBUG_INLINE Event::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_(arena),
        _cached_size_{0} {}

inline void Event::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.eid_ = {};
}
Event::~Event() {
  // @@protoc_insertion_point(destructor:workerservice.Event)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Event::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Event::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Event_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Event::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Event>(),
            ::google::protobuf::Message::GetNewImpl<Event>(),
            ::google::protobuf::Message::GetClearImpl<Event>(), &Event::ByteSizeLong,
                &Event::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Event, _impl_._cached_size_),
            false,
        },
        &Event::kDescriptorMethods,
        &descriptor_table_worker_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Event::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2> Event::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::workerservice::Event>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string data = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Event, _impl_.data_)}},
    // int64 eid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Event, _impl_.eid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Event, _impl_.eid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 eid = 1;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.eid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string data = 2;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\4\0\0\0\0\0"
    "workerservice.Event"
    "data"
  }},
};

PROTOBUF_NOINLINE void Event::Clear() {
// @@protoc_insertion_point(message_clear_start:workerservice.Event)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _impl_.eid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Event::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Event& this_ = static_cast<const Event&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Event::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Event& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:workerservice.Event)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 eid = 1;
          if (this_._internal_eid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_eid(), target);
          }

          // string data = 2;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "workerservice.Event.data");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:workerservice.Event)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Event::ByteSizeLong(const MessageLite& base) {
          const Event& this_ = static_cast<const Event&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Event::ByteSizeLong() const {
          const Event& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:workerservice.Event)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string data = 2;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data());
            }
            // int64 eid = 1;
            if (this_._internal_eid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_eid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Event::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Event*>(&to_msg);
  auto& from = static_cast<const Event&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:workerservice.Event)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_eid() != 0) {
    _this->_impl_.eid_ = from._impl_.eid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Event::CopyFrom(const Event& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:workerservice.Event)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Event::InternalSwap(Event* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
        swap(_impl_.eid_, other->_impl_.eid_);
}

::google::protobuf::Metadata Event::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace workerservice
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_worker_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
