// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker_service.proto
#ifndef GRPC_worker_5fservice_2eproto__INCLUDED
#define GRPC_worker_5fservice_2eproto__INCLUDED

#include "worker_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace workerservice {

// The worker service definition
class WorkerService final {
 public:
  static constexpr char const* service_full_name() {
    return "workerservice.WorkerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::workerservice::WorkerQueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::workerservice::WorkerQueryResponse>> AsyncGetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::workerservice::WorkerQueryResponse>>(AsyncGetReplayDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::workerservice::WorkerQueryResponse>> PrepareAsyncGetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::workerservice::WorkerQueryResponse>>(PrepareAsyncGetReplayDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest* request, ::workerservice::WorkerQueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest* request, ::workerservice::WorkerQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::workerservice::WorkerQueryResponse>* AsyncGetReplayDataRaw(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::workerservice::WorkerQueryResponse>* PrepareAsyncGetReplayDataRaw(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::workerservice::WorkerQueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::workerservice::WorkerQueryResponse>> AsyncGetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::workerservice::WorkerQueryResponse>>(AsyncGetReplayDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::workerservice::WorkerQueryResponse>> PrepareAsyncGetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::workerservice::WorkerQueryResponse>>(PrepareAsyncGetReplayDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest* request, ::workerservice::WorkerQueryResponse* response, std::function<void(::grpc::Status)>) override;
      void GetReplayData(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest* request, ::workerservice::WorkerQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::workerservice::WorkerQueryResponse>* AsyncGetReplayDataRaw(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::workerservice::WorkerQueryResponse>* PrepareAsyncGetReplayDataRaw(::grpc::ClientContext* context, const ::workerservice::WorkerQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetReplayData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetReplayData(::grpc::ServerContext* context, const ::workerservice::WorkerQueryRequest* request, ::workerservice::WorkerQueryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetReplayData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetReplayData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetReplayData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReplayData(::grpc::ServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReplayData(::grpc::ServerContext* context, ::workerservice::WorkerQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::workerservice::WorkerQueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetReplayData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetReplayData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetReplayData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::workerservice::WorkerQueryRequest, ::workerservice::WorkerQueryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::workerservice::WorkerQueryRequest* request, ::workerservice::WorkerQueryResponse* response) { return this->GetReplayData(context, request, response); }));}
    void SetMessageAllocatorFor_GetReplayData(
        ::grpc::MessageAllocator< ::workerservice::WorkerQueryRequest, ::workerservice::WorkerQueryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::workerservice::WorkerQueryRequest, ::workerservice::WorkerQueryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetReplayData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReplayData(::grpc::ServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReplayData(
      ::grpc::CallbackServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetReplayData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetReplayData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetReplayData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetReplayData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReplayData(::grpc::ServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetReplayData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetReplayData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetReplayData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReplayData(::grpc::ServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReplayData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetReplayData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetReplayData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetReplayData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetReplayData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReplayData(::grpc::ServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReplayData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetReplayData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetReplayData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::workerservice::WorkerQueryRequest, ::workerservice::WorkerQueryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::workerservice::WorkerQueryRequest, ::workerservice::WorkerQueryResponse>* streamer) {
                       return this->StreamedGetReplayData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetReplayData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetReplayData(::grpc::ServerContext* /*context*/, const ::workerservice::WorkerQueryRequest* /*request*/, ::workerservice::WorkerQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetReplayData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::workerservice::WorkerQueryRequest,::workerservice::WorkerQueryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetReplayData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetReplayData<Service > StreamedService;
};

}  // namespace workerservice


#endif  // GRPC_worker_5fservice_2eproto__INCLUDED
